var porjectview = "	<!--查看项目-->	"
    + "	<div class='layui-tab layui-tab-brief' lay-filter='docDemoTabBrief' style='margin:0px 0px'>	"
    + "	    <ul class='layui-tab-title'>	"
    + "	        <li class='layui-this'>基本信息</li>	"
    + "	        <li>消落带信息</li>	"
    + "	        <li>测窗信息</li>	"
    + "	        <li>节理信息</li>	"
    + "	        <li>优势结构面</li>	"
    + "	        <li>玫瑰花</li>	"
    + "	        <li>测窗成图信息</li>	"
    + "	    </ul>	"
    + "	    <div class='layui-tab-content' style='margin:0px 0px'>	"
    + "	        <!--基本信息-->	"
    + "	        <div class='layui-tab-item layui-show'>	"
    + "	            <form class='layui-form' style='margin-top:0px' lay-filter='projectinfoviewform'>	"
    + "	                <div class='layui-form-item'>	"
    + "	                    <label class='layui-form-label'>项目名称</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='xmmc' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	                <div class='layui-form-item'>	"
    + "	                    <div class='layui-row'>	"
    + "	                        <div class='layui-col-md6'>	"
    + "	                            <div class='grid-demo grid-demo-bg1'>	"
    + "	                                <label class='layui-form-label'>中心经度</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='zxjd' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                        <div class='layui-col-md6'>	"
    + "	                            <div class='grid-demo'>	"
    + "	                                <label class='layui-form-label'>中心纬度</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='zxwd' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	                <div class='layui-form-item'>	"
    + "	                    <div class='layui-row'>	"
    + "	                        <div class='layui-col-md3'>	"
    + "	                            <div class='grid-demo'>	"
    + "	                                <label class='layui-form-label'>行政区划</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='xzqdm' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                        <div class='layui-col-md9'>	"
    + "	                            <div class='grid-demo grid-demo-bg1'>	"
    + "	                                <label class='layui-form-label'>项目位置</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='xmwz' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	                <div class='layui-form-item'>	"
    + "	                    <div class='layui-row'>	"
    + "	                        <div class='layui-col-md6'>	"
    + "	                            <div class='grid-demo grid-demo-bg1'>	"
    + "	                                <label class='layui-form-label'>开始时间</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='xmkssj' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                        <div class='layui-col-md6'>	"
    + "	                            <div class='grid-demo'>	"
    + "	                                <label class='layui-form-label'>备注</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='bz' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </form>	"
    + "	        </div>	"
    + "	        <!--消落带-->	"
    + "	        <div class='layui-tab-item'>	"
    +"	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='xiaoluodaiinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>面积</label><div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='mianJi' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>纵长</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='zhongChang' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>体积</label><div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='tiJi' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>坡向</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='puoXiang' lay-verify='required|number'  autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>后缘高程</label><div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='hygc' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>估算厚度</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='gshd' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>名称</label><div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='xmmc' readonly='readonly' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>得分</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='projectScore'  readonly='readonly' autocomplete='off'  class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>地层岩性</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='dcyx' lay-verify='required' autocomplete='off' placeholder='请输入地层岩性' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='dcyxScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='dcyxWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>岩体结构</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ytjg' lay-verify='required' autocomplete='off' placeholder='请输入岩体结构' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ytjgScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ytjgWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>岩层产状</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='yccz' lay-verify='required' autocomplete='off' placeholder='请输入岩层产状' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ycczScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ycczWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"

    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>岸坡结构</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='apjg' lay-verify='required' autocomplete='off' placeholder='请输入岸坡结构' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='apjgScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='apjgWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>切割裂隙</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='qglx' lay-verify='required' autocomplete='off' placeholder='请输入切割裂隙' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='qglxScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='qglxWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>地貌边界</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='dmbj' lay-verify='required' autocomplete='off' placeholder='请输入地貌边界' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='dmbjScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='dmbjWeight' lay-verify='required|number'  autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>变形迹象</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='bxjx' lay-verify='required' autocomplete='off' placeholder='请输入变形迹象' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='bxjxScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='bxjxWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>岩体裂化</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ytlh' lay-verify='required' autocomplete='off' placeholder='请输入岩体裂化' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ytlhScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ytlhWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>植被覆盖</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='zbfg' lay-verify='required' autocomplete='off' placeholder='请输入植被覆盖' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='zbfgScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='zbfgWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item' style='margin:25px 0px 25px 0px;'>	"
    + "	        <div style='position:absolute;right:300px;'>	"
    + "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='editxiaoluodaisubmit' style='width:100px'>提交</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	"

    + "	        </div>	"
    + "	        <!--测窗信息-->	"
    + "	        <div class='layui-tab-item'>	"
    + "	            <table class='layui-hide' id='windowtable-view' lay-filter='windowtable-view'></table>	"
    + "	        </div>	"
    + "	        <!--节理信息-->	"
    + "	        <div class='layui-tab-item'>	"
    + "	            <table class='layui-hide' id='jielitable-view' lay-filter='jielitable-view'></table>	"
    + "	        </div>	"
    + "	        <!--优势结构面-->	"
    + "	        <div class='layui-tab-item'>	"
    + "	            <table class='layui-hide' id='jiegoutables-view' lay-filter='jiegoutables-view'></table>	"
    + "	        </div>	"
    + "	        <!--节理玫瑰花-->	"
    + "	        <div class='layui-tab-item'>	"
    + "	            <div id='autodatachart' class='layui-tab-item layui-show' style='width:790px;height:540px;top:40px'></div>	"
    + "	        </div>	"
    + "	        <!--节理成图-->	"
    + "	        <div class='layui-tab-item'>	"
    + "	            <div> 斜坡体</div>"
    + "	        </div>	"

    + "	    </div>	"
    + "	</div>	";

var addNewproject = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='addprojectinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>项目名称</label>	"
    + "	        <div class='layui-input-block'>	"
    + "	            <input type='text' name='xmmc' autocomplete='off' placeholder='请输入' lay-verify='required' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>中心经度</label><div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='zxjd' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>中心纬度</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='zxwd' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>行政区划</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	            <select id='provinceid' name='province' lay-verify='required'>	"
    + "	                <option value=''>省/市</option>	"
    + "	                <option value='0'>重庆市</option>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	            <select id='cityid' name='city' lay-verify='required'>	"
    + "	                <option value=''>市辖区/县</option>	"
    + "	                <option value='0'>市辖区</option>	"
    + "	                <option value='1'>县</option>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	            <select id='districtid' name='district' lay-verify='required'>	"
    + "	                <option value=''>区/县</option>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>项目位置</label>	"
    + "	        <div class='layui-input-block'>	"
    + "	            <input type='text' name='xmwz' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>开始时间</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' id='xmkssjid' name='xmkssj' lay-verify='date' placeholder='YYYY-MM-DD' autocomplete='off' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>备注</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='bz' placeholder='请输入' autocomplete='off' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
  
    + "	    <div class='layui-form-item' style='margin:25px 0px 25px 0px;'>	"
    + "	        <div style='position:absolute;right:300px;'>	"
    + "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='addprojectinfosubmit' style='width:100px'>提交</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	";

var pdfWindow = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='querypdfWindowinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>测窗</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <select id='windowIdSelectpdf'  lay-verify='required' name='windowId'>	"
    + "	                            <option value=''>请选择</option>	"
    + "	                        </select>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>模型</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <select id='modleIdSelect' name='modleId'>	"
    + "	                            <option value=''>请选择</option>	"
    + "	                        </select>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item' style='margin-top:5px;height: 40px'>	"
    + "	        <div style='position:absolute;right:15px;'>	"
    + "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='querypdfWindowsubmit' style='width:100px'>查询</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	"
    + "	<div id='pdfwinchart' class='layui-tab-item layui-show' style='width:900px;height:600px'></div>	";

var pdfjieli = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='querypdfjieliinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md10'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>测窗</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <select id='jieliIdSelectpdf'  lay-verify='required' name='jieliId'>	"
    + "	                            <option value=''>请选择</option>	"
    + "	                        </select>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md10'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>是否闭合</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='checkbox' name='isClose' checked='' value='0' lay-verify='required'  lay-skin='switch' lay-text='是|否' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md10'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                  <label class='layui-form-label'>采集人</label>	"
    + "	                     <div class='layui-input-block'>	"
    + "	                        <input type='text' name='collector' autocomplete='off' placeholder='请输入' lay-verify='required' class='layui-input' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item' style='margin-top:35px;height: 40px'>	"
    + "	        <div style='position:absolute;right:15px;'>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='querypdfjielisubmit' style='width:100px'>素描</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	" ;
var projietHtml = "	<div class='layui-tab layui-tab-brief' lay-filter='projecrListTuCeng'>								"
    + "		<ul class='layui-tab-title'>							"
    + "			<li lay-id='111' class='layui-this' style='width:30%;padding-top: 10px;'>项目列表</li>						"
    + "			<li lay-id='222' style='width:30%;padding-top: 10px;'>图层列表</li>						"
    + "		</ul>							"
    + "		<div class='layui-tab-content'>							"
    + "			<div class='layui-tab-item layui-show'>						"
    + "						<div id='projectbyarea'>			"
    + "						</div>			"
    + "			</div>						"
    + "			<div class='layui-tab-item'>						"
    + "				 <div id='prjlayerlist'></div>			"
    + "			</div>						"
    + "		</div>							"
    + "	</div>								";

var addNewXiePuo = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='addprojectinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>斜坡名称</label>	"
    + "	        <div class='layui-input-block'>	"
    + "	            <input type='text' name='xmmc' autocomplete='off' placeholder='请输入' lay-verify='required' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>开始时间</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' id='xmkssjid' name='xmkssj' lay-verify='date' placeholder='YYYY-MM-DD' autocomplete='off' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>备注</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='bz' placeholder='请输入' autocomplete='off' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"

    + "	    <div class='layui-form-item' style='margin:25px 0px 25px 0px;'>	"
    + "	        <div style='position:absolute;right:300px;'>	"
    + "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='addprojectinfosubmit' style='width:100px'>提交</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	";

var xiePuoSteepHillHtml = "	<!--隐患识别-->	"
    + "	<div class='layui-tab layui-tab-brief'  style='margin:0px 0px'>	"
    + "	 <form class='layui-form' action='' style='margin-top:5px;margin-right:5px;' lay-filter='xiePuoSteepHillFilter'>	"
    + "      <fieldset class='layui-elem-field layui-field-title' style='margin-top: 5px;'><legend>地形地貌  <input type='text' name='dxdm' lay-verify='required|number'  readonly='readonly' style='border:none;width: 60px;margin-left: 20px;' /></legend></fieldset>"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'style='width:90px;' >岸坡坡度</label>	"
    + "	        <div class='layui-input-inline' style='width:90px;'>	"
    + "	            <select id='appdId' lay-filter='appdSelect'   name='appd' lay-verify='required'>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(1)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px' id='appdts'   />	"
    + "	        </div>	"

    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label' style='width:90px;' >岸坡结构</label>	"
    + "	        <div class='layui-input-inline' style='width:90px;'>	"
    + "	            <select id='apjgId' name='apjg' lay-filter='apjgSelect' lay-verify='required'>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(2)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px' id='apjgts'  />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label' style='width:90px;' >斜坡边界</label>	"
    + "	        <div class='layui-input-inline' style='width:90px;'>	"
    + "	            <select id='xpbjId' name='xpbj' lay-filter='xpbjSelect' lay-verify='required'>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(3)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  id='xpbjts' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "      <fieldset class='layui-elem-field layui-field-title' style='margin-top: 10px;'><legend>地质构造 <input type='text' name='dzgz' lay-verify='required|number'  readonly='readonly' style='border:none;width: 60px;margin-left: 20px;' /></legend></fieldset>"
    + "    <div class='layui-form-item'>"
    + "        <label class='layui-form-label' style='width:90px;' >岩性岩组</label>"
    + "        <div class='layui-input-inline' style='width:90px;'>"
    + "            <select id='yxyzId' name='yxyz' lay-filter='yxyzSelect' lay-verify='required'>"
    + "            </select>"
    + "        </div>"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(4)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "        <div class='layui-input-inline' style='width:30px;'>"
    + "              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  id='yxyzts' />"
    + "        </div>"
    + "    </div>"
    + "    <div class='layui-form-item'>"
    + "        <label class='layui-form-label' style='width:90px;' >软弱层</label>"
    + "        <div class='layui-input-inline' style='width:90px;'>"
    + "            <select id='rucId' name='ruc' lay-filter='rucSelect' lay-verify='required'>"
    + "            </select>"
    + "        </div>"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(5)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "        <div class='layui-input-inline' style='width:30px;'>"
    + "              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  id='rrcts' />"
    + "        </div>"
    + "    </div>"
    + "      <fieldset class='layui-elem-field layui-field-title' style='margin-top: 10px;'><legend>工程地质 <input type='text' name='gcdz' lay-verify='required|number'  readonly='readonly' style='border:none;width: 60px;margin-left: 20px;' /></legend></fieldset>"
    + "    <div class='layui-form-item'>"
    + "        <label class='layui-form-label' style='width:90px;' >岩体结构</label>"
    + "        <div class='layui-input-inline' style='width:90px;'>"
    + "            <select id='ytjgId' name='ytjg' lay-filter='ytjgSelect' lay-verify='required'>"
    + "            </select>"
    + "        </div>"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(6)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "        <div class='layui-input-inline' style='width:30px;'>"
    + "              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  id='ytjgts' />"
    + "        </div>"
    + "    </div>"



    + "    <div class='layui-form-item'>"
    + "        <label class='layui-form-label' style='width:90px;'>岩体风化程度</label>"
    + "        <div class='layui-input-inline' style='width:90px;'>"
    + "            <select id='ytfhId' name='ytfh' lay-filter='ytfhSelect' lay-verify='required'>"
    + "            </select>"
    + "        </div>"

    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(7)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "        <div class='layui-input-inline' style='width:30px;'>"
    + "              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  id='ytfhts' />"
    + "        </div>"
    + "    </div>"
    + "    <div class='layui-form-item'>"
    + "        <label class='layui-form-label' style='width:90px;' >岩体劣化程度</label>"
    + "        <div class='layui-input-inline' style='width:90px;' >"
    + "            <select id='ytlhId' name='ytlh' lay-filter='ytlhSelect' style='width:90px;' lay-verify='required'>"
    + "            </select>"
    + "        </div>"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(8)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "        <div class='layui-input-inline' style='width:30px;'>"
    + "              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  id='ytlhts' />"
    + "        </div>"
    + "    </div>"
    + "    <div class='layui-form-item'>"
    + "	            <label class='layui-form-label' style='width: 30px'>总分</label>	"
    + "	            <div class='layui-input-inline'>	"
    + "	                <input type='text' name='score' style='border:none;font-weight: bold;font-size: 24px;' lay-verify='required|number' autocomplete='off'  readonly='readonly' class='layui-input' />	"
    + "	           </div>	"
    + "    </div>"
    + "    <div class='layui-form-item'>"
   // + "	            <label class='layui-form-label' style='width: 90px'>结论</label>	"
    + "	            <div class='layui-input-inline' style='width:95%;margin-left: 10px' >	"
    + "	                <input type='text' name='jieLun' style='border:none;font-size: 20px;' lay-verify='required' autocomplete='off'  readonly='readonly' class='layui-input' />	"
    + "	           </div>	"
    + "    </div>"
    + "	    <div class='layui-form-item' style='margin:25px 0px 25px 0px;'>	"
    + "	        <div style='position:absolute;right:150px;'>	"
    //+ "	            <button type='button' class='layui-btn layui-btn-normal' id='LAY-component-form-setval'>赋值</button> "
    //+ "	            <button type = 'button' class='layui-btn layui-btn-normal' id = 'LAY-component-form-getval' > 计算</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='xiePuoSteepHillFilterSubmit' style='width:100px'>提交</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	  </form>	"
    + "	</div>	";
var xiepoTable = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='queryXiepoinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>斜坡状态</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <select name='jieLun'>	"
    + "	                            <option value=''>请选择</option>	"
    + "	                            <option value='斜坡消落区发生演化可能性大'>斜坡消落区发生演化可能性大</option>	"
    + "	                            <option value='斜坡消落区发生演化可能性中'>斜坡消落区发生演化可能性中</option>	"
    + "	                            <option value='斜坡消落区发生演化可能性小'>斜坡消落区发生演化可能性小</option>	"
    + "	                        </select>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div style='position:absolute;right:15px;'>	"
    + "	                    <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	                    <button type='submit' class='layui-btn' lay-submit='' lay-filter='queryXieposubmit' style='width:100px'>查询</button>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	"

    + "	<script type='text/html' id='processedPatrolButon'>                                                      "
    //+ "           {{#  if(d.status != 0){ }}"
    //+ "		        <a class='layui-btn layui-btn-xs' lay-event='edit'>查看坡面</a>                       "
    //+ "          {{#  } }} "
    + "			    <a class='layui-btn  layui-btn-xs' lay-event='chuli'>编辑</a>  "
    + "          {{#  if(d.srcList != ''){ }}"
    + "			    <a class='layui-btn layui-btn-normal layui-btn-xs' lay-event='detail'>查看</a>  "
    + "          {{#  } }} "

    + "			    <a class='layui-btn layui-btn-danger layui-btn-xs' lay-event='delete'>删除</a>  "
    + "		</script>                                                                             "
    + "	<table class='layui-hide' id='xiepotable-view' lay-filter='xiepotable-view'></table> 	<script type='text/html' id='xie-puo-add'><div class='layui-btn-container'>"
    + "  <button class='layui-btn layui-btn' style = 'font-size:14px;width:150px' lay-event='xie-puo-add'> 添加识别单元</button>"
    + "  <button class='layui-btn layui-btn layui-btn-danger' style = 'font-size:14px;width:150px' lay-event='xie-puo-del'> 单元批量删除</button>"
    + "  <button class='layui-btn layui-btn  layui-btn-normal' style = 'font-size:14px;width:150px' lay-event='add-model'> 添加识别模型</button>"
    + "  <button class='layui-btn layui-btn  layui-btn-warm' style = 'font-size:14px;width:150px' lay-event='level-show'> 分级显示</button>"
    +"</div ></script> ";


var srcChaKan =  "<ul id='xiepochakan'>                                       "
    + "    <li><img id='appdSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岸坡坡度'></li> "
    + "    <li><img id='apjgSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岸坡结构'></li> "
    + "    <li><img id='xpbjSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='斜坡边界'></li> "
    + "    <li><img id='yxyzSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岩性岩组'></li> "
    + "    <li><img id='rucSrcId'  style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='软弱层'></li> "
    + "    <li><img id='ytjgSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岩体结构'></li> "
    + "    <li><img id='ytfhSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岩体风化程度'></li> "
    + "    <li><img id='ytlhSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岩体裂化程度'></li> "
    +"</ul>                                                 "      
var srcChaKan = "<ul id='xiepochakan'>                                       "
    + "    <li><img id='appdSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岸坡坡度'></li> "
    + "    <li><img id='apjgSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岸坡结构'></li> "
    + "    <li><img id='xpbjSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='斜坡边界'></li> "
    + "    <li><img id='yxyzSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岩性岩组'></li> "
    + "    <li><img id='rucSrcId'  style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='软弱层'></li> "
    + "    <li><img id='ytjgSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岩体结构'></li> "
    + "    <li><img id='ytfhSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岩体风化程度'></li> "
    + "    <li><img id='ytlhSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岩体裂化程度'></li> "
    + "</ul>                                                 "      
var modelAddHaveHtml = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='modelAddHaveinfoform'>	"
    + "	    <div class='layui-form-item'>	"
        + "   <div class='layui-inline'>                                                                                              "
        + "   	<label class='layui-form-label'>选择项目</label>                                                                      "
        + "  	 <div class='layui-input-inline'>                                                                                        "
    + "     	   <select name='projectId' id='checkprojectId'  lay-filter='projectIdFilter' lay-verify='required'>                                                                                                 "

        + "     	</select>                                                                                                             "
        + "   	</div>                                                                                                                  "
        + "   </div>                                                                                                                  "
    + "	     </div>	"
    + " <div class='layui-form-item'>                                                                                             "
    + "   <div class='layui-input-block' style='float: right;margin-top:25px;' >                                                                                         "
    + "     <button type='submit' class='layui-btn' lay-submit='' lay-filter='modelAddHaveSubmit'>立即提交</button>                            "
    + "   </div>                                                                                                                  "
    + " </div>                                                                                                                    "
    + "	</form>	"

var fromModelShiBie =  "<script type='text/html' id='modelCaoZuoButonn'>                                                      "
                        //+ "			    <a class='layui-btn  layui-btn-xs' lay-event='chuli'>识别</a>  "
                        //+ "          {{#  if(d.srcList != ''){ }}"
                        //+ "			    <a class='layui-btn layui-btn-normal layui-btn-xs' lay-event='detail'>查看</a>  "
                        //+ "          {{#  } }} "

                        + "			    <a class='layui-btn layui-btn-danger layui-btn-xs' lay-event='delete'>删除</a>  "
                        + "		</script>                                                                             "
                        +"<table class='layui-hide' id='modelShiBie-view' lay-filter='modelShiBie-view'></table>"
                        + "<script type='text/html' id='model-add'><div class='layui-btn-container'>"
                        + "  <button class='layui-btn' style = 'font-size:14px;width:150px' lay-event='model-add'> 添加识别因子</button>"
                        + "  <button class='layui-btn layui-btn-normal' style = 'font-size:14px;width:150px' lay-event='model-add-have'> 引用已有模型</button>"
                        + "  <button class='layui-btn layui-btn-warm' style = 'font-size:14px;width:150px' lay-event='quanZhong-add'> 设置模型权重</button>"
                        + "</div ></script> "

                        + " <form class='layui-form' action='' lay-filter='xiePuoModelAddFilter' id='modelAddform'>                                                                                           "
                        + " <fieldset class='layui-elem-field layui-field-title' style='margin-top: 20px;'>        "
                        + " 	<legend>指标识别新增</legend>                                                       "
                        + " </fieldset>                                                                            "

                        + " <div class='layui-form-item'>                                                                                             "
                        + "   <div class='layui-inline'>                                                                                              "
                        + "   	<label class='layui-form-label'>指标类型</label>                                                                      "
                        + "  	 <div class='layui-input-inline'>                                                                                        "
                        + "     	<select name='indicatorType' id='dicIndicatorType'  lay-filter='indicatorType' lay-verify='required'>                                                                                                 "

                        + "     	</select>                                                                                                             "
                        + "   	</div>                                                                                                                  "
                        + "   </div>                                                                                                                  "
                        + "   <div class='layui-inline'>                                                                                              "
                        + "		<label class='layui-form-label'>识别指标</label>                                                                      "
                        + "   	<div class='layui-input-inline'>                                                                                        "
                        + "     	<select name='identificatIndex' id='identificatIndex' lay-verify='required'>                                                                                                 "

                        + "     	</select>                                                                                                             "
                        + "   	</div>                                                                                                                  "
                        + "   </div>                                                                                                                  "
                        + "   <div class='layui-inline'>                                                                                              "
                        + "		<label class='layui-form-label'>指标因子</label>                                                                      "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='indexFactor' lay-verify='required' autocomplete='off' class='layui-input'>                "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "
                        + "	<div class='layui-inline'>                                                                                                "
                        + "		<label class='layui-form-label'>因子值</label>                                                                        "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='factorValue' lay-verify='required|number' autocomplete='off' class='layui-input'>         "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "
                        + " </div>                                                                                                                    "
                        + "                                                                                                                           "
                        + "                                                                                                                           "
                        + " <div class='layui-form-item layui-form-text'>                                                                             "
                        + "   <label class='layui-form-label'>评判标准</label>                                                                      "
                        + "   <div class='layui-input-block'>                                                                                         "
                        + "     <textarea placeholder='请输入评判标准' name='evaluationCriteria' style='width: 1162px;'  lay-verify='required' class='layui-textarea'></textarea>                                                 "
                        + "   </div>                                                                                                                  "
                        + " </div>                                                                                                                    "
                        + "                                                                                                                           "
                        + " <div class='layui-form-item'>                                                                                             "
                        + "   <div class='layui-input-block' style='margin-left: 80%' >                                                                                         "
                        + "     <button type='submit' class='layui-btn' lay-submit='' lay-filter='modelShibieSubmit'>立即提交</button>                            "
                        //+ "     <button type='reset' class='layui-btn layui-btn-primary'>重置</button>                                                "
                        + "   </div>                                                                                                                  "
                        + " </div>                                                                                                                    "
                        + "</form>                                                                                                                     "
                        + " <form class='layui-form' action='' lay-filter='quanZhongAddFilter' id='quanZhongAddform'>                                                                                           "
                        + " <fieldset class='layui-elem-field layui-field-title' style='margin-top: 20px;'>        "
                        + " 	<legend>权重编辑</legend>                                                       "
                        + " </fieldset>                                                                            "

                        + " <div class='layui-form-item'>                                                                                             "
                        + "	<div class='layui-inline'>                                                                                                "
                        + "		<label class='layui-form-label'>地形地貌</label>                                                                        "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='dxdm' lay-verify='required|number' autocomplete='off' class='layui-input'>         "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "
                        + "	<div class='layui-inline'>                                                                                                "
                        + "		<label class='layui-form-label'>岸坡坡度</label>                                                                        "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='appd' lay-verify='required|number' autocomplete='off' class='layui-input'>         "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "
                        + "	<div class='layui-inline'>                                                                                                "
                        + "		<label class='layui-form-label'>岸坡结构</label>                                                                        "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='apjg' lay-verify='required|number' autocomplete='off' class='layui-input'>         "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "
                        + "	<div class='layui-inline'>                                                                                                "
                        + "		<label class='layui-form-label'>斜坡边界</label>                                                                        "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='xpbj' lay-verify='required|number' autocomplete='off' class='layui-input'>         "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "

                        + " </div>                                                                                                                    "
                        + " <div class='layui-form-item'>                                                                                             "
                        + "	<div class='layui-inline'>                                                                                                "
                        + "		<label class='layui-form-label'>地质构造</label>                                                                        "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='dzgz' lay-verify='required|number' autocomplete='off' class='layui-input'>         "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "
                        + "	<div class='layui-inline'>                                                                                                "
                        + "		<label class='layui-form-label'>岩性岩组</label>                                                                        "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='yxyz' lay-verify='required|number' autocomplete='off' class='layui-input'>         "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "
                        + "	<div class='layui-inline'>                                                                                                "
                        + "		<label class='layui-form-label'>软弱层</label>                                                                        "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='rrc' lay-verify='required|number' autocomplete='off' class='layui-input'>         "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "
                        + " </div>                                                                                                                    "
                        + " <div class='layui-form-item'>                                                                                             "
                        + "	<div class='layui-inline'>                                                                                                "
                        + "		<label class='layui-form-label'>工程地质</label>                                                                        "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='gcdz' lay-verify='required|number' autocomplete='off' class='layui-input'>         "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "
                        + "	<div class='layui-inline'>                                                                                                "
                        + "		<label class='layui-form-label'>岩体结构</label>                                                                        "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='ytjg' lay-verify='required|number' autocomplete='off' class='layui-input'>         "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "
                        + "	<div class='layui-inline'>                                                                                                "
                        + "		<label class='layui-form-label'>岩体风化</label>                                                                        "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='ytfh' lay-verify='required|number' autocomplete='off' class='layui-input'>         "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "
                        + "	<div class='layui-inline'>                                                                                                "
                        + "		<label class='layui-form-label'>岩体劣化</label>                                                                        "
                        + "		<div class='layui-input-inline'>                                                                                      "
                        + "			<input type='text' name='ytlh' lay-verify='required|number' autocomplete='off' class='layui-input'>         "
                        + "		</div>                                                                                                                "
                        + "	</div>                                                                                                                    "

                        + " </div>                                                                                                                    "                 
                        + " <div class='layui-form-item'>                                                                                             "
                        + "   <div class='layui-input-block' style='margin-left: 80%' >                                                                                         "
                        + "     <button type='submit' class='layui-btn' lay-submit='' lay-filter='quanZhongSubmit'>立即提交</button>                            "
                        //+ "     <button type='reset' class='layui-btn layui-btn-primary'>重置</button>                                                "
                        + "   </div>                                                                                                                  "
                        + " </div>                                                                                                                    "
                        + "</form>                                                                                                                     ";